from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from .academic_entity import AcademicEntity
from .semester import Semester


class Course(AcademicEntity):
    # Note: We do not use the "identifier" primary key from AcademicEntity, because Courses in themselves have a
    # unique code. Therefore we use that instead of an autogenerated key.
    code = models.TextField(
        unique=True,
        help_text=_("The courses code (e.g., DLBBIM01)")
    )
    semester = models.ForeignKey(
        to=Semester,
        related_name='courses',
        on_delete=models.CASCADE,
        help_text=_("The semester in which this course is offered")
    )
    description = models.TextField(
        blank=True,
        help_text=_("Detailed description of the course content")
    )
    ects = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(30)],
        help_text=_("The number of ECTS credits for this course")
    )

    class Meta:
        ordering = ['semester', 'name']
        verbose_name = _("course")
        verbose_name_plural = _("courses")
        indexes = [
            models.Index(fields=['semester']),
        ]

    def __str__(self):
        return f"{self.name} ({self.ects} ECTS)"
