# Generated by Django 5.2.1 on 2025-06-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_quicklink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='identifier',
            field=models.CharField(help_text='The course identifier (e.g., DLBBIM01)', primary_key=True, serialize=False, unique=True),
        ),
    ]
