# Generated by Django 5.2.1 on 2025-06-02 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_course_identifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('AVL', 'Verfügbar'), ('ENR', 'Eingeschrieben'), ('CMP', 'Bestanden'), ('FAL', 'Nicht bestanden')], db_index=True, help_text='The current status of this enrollment', max_length=3),
        ),
        migrations.CreateModel(
            name='UserTablePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(help_text='Identifier for the table these preferences apply to', max_length=100)),
                ('filter_settings', models.JSONField(default=dict, help_text='JSON representation of the filter settings')),
                ('user', models.ForeignKey(help_text='The user these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='table_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user table preference',
                'verbose_name_plural': 'user table preferences',
                'indexes': [models.Index(fields=['user', 'table_id'], name='dashboard_u_user_id_feb637_idx')],
                'unique_together': {('user', 'table_id')},
            },
        ),
    ]
