# Generated by Django 5.2.3 on 2025-07-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_displaycourse_alter_enrollment_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayCourse',
        ),
        migrations.AlterUniqueTogether(
            name='usertablepreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertablepreference',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['course', 'exam_type'], 'verbose_name': 'exam', 'verbose_name_plural': 'exams'},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='dashboard_c_degree__a65633_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='degree',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', help_text='The courses code (e.g., DLBBIM01)', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='identifier',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('AVL', 'Available'), ('ENR', 'Enrolled'), ('CMP', 'Completed'), ('ACK', 'Acknowledged'), ('FAL', 'Failed')], db_index=True, help_text='The current status of this enrollment', max_length=3),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('WB', 'Advanced workbook'), ('PO', 'Portfolio'), ('RE', 'Project report'), ('WE', 'Written exam'), ('PR', 'Presentation'), ('CS', 'Case study'), ('TH', 'Theses')], db_index=True, help_text='The type of examination', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='time_model',
            field=models.IntegerField(choices=[(36, 'Full-time'), (48, 'Part-time 1'), (72, 'Part-time 2')], default=36, verbose_name='time model'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['semester'], name='dashboard_c_semeste_d49c11_idx'),
        ),
        migrations.DeleteModel(
            name='UserTablePreference',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='exam',
        ),
    ]
