# Generated by Django 5.2.3 on 2025-07-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_displaycourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.TextField(help_text='The courses code (e.g., DLBBIM01)', unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.OneToOneField(help_text='The course this exam is for', on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='dashboard.course'),
        ),
    ]
